### ISSUE TITLE
The version of wallet for windows 64 bits not working

### ISSUE THREAD

**Issue by Albatroz4402** [DigitalNoteXDN/digitalnotewallet#10]
I downloaded the version of wallet for windows 64 bits, but when i open the archive .exe i receive the message of "DigitalNote wallet already running" but the program of wallet dont is open.

**Comment by AuCRHI** [comment]
Please go to our support channel for help.

https://discordapp.com/invite/E6NQYwh <https://discordapp.com/invite/E6NQYwh>

The DigitalNote XDN dev team
AuCRHI



On 28 Oct 2018, at 00:01, Albatroz4402 <notifications@github.com> wrote:

I downloaded the version of wallet for windows 64 bits, but when i open the archive .exe i receive the message of "DigitalNote wallet already running" but the program of wallet dont is open.
