### ISSUE TITLE
Compile on Windows via MSYS2

### ISSUE THREAD

**Issue by BearBang7** [DigitalNoteXDN/digitalnotewallet#5]
Is that possible generate .exe from source code using msys2 ?!
Which packages or libraries are needed ?
Please add a guidance in wiki section.

**Comment by DrCryptoToad** [comment]
Although we have not compiled on msys2, it should be possible.  We will add more information on our readme for compile help as soon as possible.  Dependencies needed: Boost 1.55+ and QT (we recommend 5.10.1+).
