### ISSUE TITLE
DigitalNote wallet is saving date Takes for ever !

### ISSUE THREAD

**Issue by BearBang7** [DigitalNoteXDN/digitalnotewallet#7]
Windows 8.1 x64.
DigitalNote wallet is saving data Please Wait ... .
It takes for ever and never ended.

**Comment by DrCryptoToad** [comment]
Hi, this has been an issue for a couple years before the new dev team started working on the project.  We will attempt to fix it but it happens on other versions of Windows as well.  I've found that if you close the wallet too early it seems to trigger the bug.  Try opening the wallet and waiting at least a couple of minutes before closing it.  You can also try resyncing your blockchain and making sure you wait a couple of minutes before closing the wallet the first time you open after resyncing.

**Comment by skironDotNet** [comment]
No it wasn't "an issue for a couple years before" go to previous XDN repo (before take over) and the GUI works just fine. I use Linux version GUI and the new one from this repo is buggy

**Comment by DrCryptoToad** [comment]
@skironDotNet yes it is absolutely an issue for a couple years before.  I personally experienced the issue as far back as early 2017 and asked dNote about it.  Not sure why you are trying to argue with devs who actually handle working with the code.  If you compile the old repo you will experience the same problems.  Please do not comment unless you have something worthwhile to add to the conversation, thank you.

**Comment by BearBang7** [comment]
@DrCryptoToad so you dev team can't resolve a bug on wallet ?

**Comment by DrCryptoToad** [comment]
@BearBang7 we haven't had a chance to look at it in depth, as it is non-critical and we have been busy with more important changes and other operations dealing with exchanges.  It's added to the list though.  This thread is closed as we do not need incessant bickering (which wastes more of our time), just a bug report thank you.
