### ISSUE TITLE
GUI: Not able to send 20,000 XDN to exchange

### ISSUE THREAD

**Issue by simbadMarino** [DigitalNoteXDN/digitalnotewallet#8]
**Software version:**
1.0.16b GUI wallet

**Description:**
Transaction not confirmed if XDN amount is 20,000 to bittrex exchange.

**Steps:**
1. Set receiver"Pay to" address
2. Set amount to 20000.00000000 XDN
3. Set fee = 0.00100000 XDN(default)
4. Set bittrex Payment ID
5.  Set Anonimity level = 2(default)
5. Click "Send button"

**Expected Results:**
After some block confirmations transaction status indicator appears(small clock) as red and transaction get constantly validated until confirmed.

**Actual Results:**
No matter how much blocks are discovered the status indicator never appears and after ~24hrs transaction is cancelled automatically.

**Current system version:**
Windows 10 & Windows 7

**Comment by AuCRHI** [comment]
Hello thanks for the information. We have tested this on Mac, Linux and Windows today and it went through to Bittrex  and confirmed in under 10 minutes. Always BACKUP Your wallet before you do anything. try and reset your wallet and check out our discord channel for support. https://discordapp.com/invite/E6NQYwh
